In [23]:
import helpers
import numpy as np

#helpers.npNicePrint(arr)

data = """#.##..##.
..#.##.#.
##......#
##......#
..#.##.#.
..##..##.
#.#.##.#.

#...##..#
#....#..#
..##..###
#####.##.
#####.##.
..##..###
#....#..#"""
with open("input_13.txt", 'r') as f:
    data = f.read().strip()

arrs = []

data = data.split("\n\n")

for input_str in data:
    arrs.append(np.array([[int(char == "#") for char in line] for line in input_str.strip().split("\n")]))
arrs

[array([[1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0],
        [1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1],
        [1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
        [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0],
        [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
        [1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0],
        [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1],
        [0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1],
        [0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1]]),
 array([[1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
        [1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1],
        [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
        [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
        [

In [24]:
import numpy as np

def split_and_mirror(arr):
    splits = []

    # Vertical splits
    for split_point in range(1, arr.shape[1]-1):
        left_side = arr[:, :split_point]
        right_side = arr[:, split_point:]
        if left_side.size > 0 and right_side.size > 0:
            reversed_right_side = np.flip(right_side, axis=1)
            print(left_side, right_side)
            splits.append((np.concatenate((left_side, reversed_right_side), axis=1), split_point, "vertical"))

    # Horizontal splits
    for split_point in range(1, arr.shape[0]-1):
        upper_part = arr[:split_point, :]
        lower_part = arr[split_point:, :]
        if upper_part.size > 0 and lower_part.size > 0:
            reversed_lower_part = np.flip(lower_part, axis=0)
            splits.append((np.concatenate((upper_part, reversed_lower_part), axis=0), split_point, "horizontal"))

    return splits


In [45]:
def get_plit_points(arr):
    for split_point in range(1,arr.shape[1]):
        left_side = arr[:, :split_point]
        right_side = arr[:, split_point:]
        min_length = min(left_side.shape[1], right_side.shape[1])
        left_side = arr[:, split_point-min_length:split_point]
        right_side = np.flip(arr[:, split_point:split_point+min_length], axis=1)
        #rint(min_length, left_side, right_side)
        if np.array_equal(left_side, right_side):
            print(f"answer horizontal split {split_point}")
            return split_point
    for split_point in range(1,arr.shape[0]):
        left_side = arr[:split_point, :]
        right_side = arr[split_point:, :]
        min_length = min(left_side.shape[0], right_side.shape[0])
        left_side = arr[split_point-min_length:split_point, :]
        right_side = np.flip(arr[split_point:split_point+min_length, :], axis=0)
        #print(left_side, right_side)
        #rint(min_length, left_side, right_side)
        if np.array_equal(left_side, right_side):
            print(f"answer vertical split {split_point}")
            return split_point * 100
    return "error"
ans = 0       
for arr in arrs:  
    print(arr)
    ans += get_plit_points(arr)
ans

[[1 0 1 0 1 1 0 1 1 0 1]
 [1 0 0 1 0 0 1 1 1 1 0]
 [1 0 1 1 1 1 1 0 0 1 1]
 [1 0 1 1 0 0 1 1 1 1 0]
 [1 1 0 1 0 0 1 1 1 1 0]
 [0 0 1 0 0 0 1 0 0 1 0]
 [1 1 0 0 0 1 0 0 0 0 1]
 [0 0 0 0 1 1 0 0 0 0 1]
 [1 1 0 1 1 0 1 0 0 1 0]
 [1 0 0 1 0 1 1 0 0 1 1]
 [1 1 0 1 1 1 0 1 1 0 1]
 [0 0 0 1 0 1 0 1 1 0 1]
 [0 1 0 1 0 1 0 1 1 0 1]
 [1 1 0 1 1 1 0 1 1 0 1]
 [1 0 0 1 0 1 1 0 0 1 1]]
answer horizontal split 8
[[1 1 0 1 0 0 0 1 0 1 0]
 [1 1 0 1 1 0 0 1 0 1 0]
 [0 1 0 1 1 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 1 0 0 1]
 [0 0 1 1 1 1 1 1 0 0 1]
 [0 1 0 1 1 0 0 0 0 0 0]
 [1 1 0 1 1 0 0 1 0 1 0]
 [1 1 0 1 0 0 0 1 0 1 0]
 [0 0 0 1 1 0 0 0 1 0 0]
 [0 0 0 1 0 1 1 1 0 0 1]
 [1 0 0 1 1 1 1 1 1 1 0]
 [0 0 1 0 1 1 0 1 1 1 0]
 [0 0 1 1 1 0 1 1 0 1 0]
 [0 0 1 1 0 1 1 0 1 1 0]
 [0 0 1 0 1 0 0 1 1 0 0]]
answer vertical split 4
[[1 0 0 0 0 0 1 1 1 0 0 1 1 1 0]
 [0 1 1 1 0 0 0 0 1 0 0 1 0 0 0]
 [0 1 0 0 1 0 1 0 0 1 1 0 0 1 0]
 [1 1 0 1 1 0 1 0 0 1 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 1 0 0 1 0 1 0]
 [0 1 1 1 0 1 0 0 1 0 0 1 0 0 1]


30158

In [26]:
[[1 1 1 1 1 1 1 1 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1]
 [1 0 1 0 0 1 0 1 1 1 1 1 0]
 [1 0 1 1 1 1 1 1 1 0 0 1 0]
 [1 0 1 1 1 1 0 1 0 1 0 0 1]
 [1 1 1 0 0 1 1 1 1 1 0 1 0]
 [1 0 1 0 0 1 0 1 0 0 1 1 0]
 [0 0 1 1 1 1 0 0 0 0 1 0 1]
 [0 0 1 1 1 1 0 0 0 1 0 0 0]
 [1 0 1 0 0 1 0 1 0 1 0 0 1]
 [1 0 1 1 1 1 0 1 0 0 0 0 0]
 [1 0 1 1 1 1 0 1 0 0 0 0 0]]

[array([[1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0],
        [1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1],
        [1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
        [1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0],
        [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0],
        [1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
        [1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0],
        [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1],
        [0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1],
        [0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
        [1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1],
        [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1]]),
 array([[1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
        [1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1],
        [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1],
        [0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0],
        [1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
        [