In [178]:
import numpy as np
data = """
../.# => ##./#../...
.#./..#/### => #..#/..../..../#..#
"""
with open("input_21.txt", 'r') as f:
    data = f.read()

data = [x for x in data.split("\n") if not x == ""]

#data= data.replace("\n", "")

grid = np.array([[0,1,0],[0,0,1],[1,1,1]])

In [179]:
data

['../.. => ###/.../#..',
 '#./.. => #../.#./###',
 '##/.. => #../###/#..',
 '.#/#. => .#./##./#.#',
 '##/#. => .#./.../...',
 '##/## => .../#../#.#',
 '.../.../... => #.##/#.../..##/.##.',
 '#../.../... => .#../#..#/###./#.##',
 '.#./.../... => ..../###./.###/##..',
 '##./.../... => .###/##../.#.#/..#.',
 '#.#/.../... => ..#./...#/.##./#.##',
 '###/.../... => ##.#/..../#.../....',
 '.#./#../... => .##./..../.##./.###',
 '##./#../... => .##./##../#.#./#.#.',
 '..#/#../... => .#../####/##.#/##.#',
 '#.#/#../... => .##./##.#/#..#/#...',
 '.##/#../... => .#../.#.#/####/....',
 '###/#../... => .###/#.#./.#../...#',
 '.../.#./... => ##.#/####/##../#..#',
 '#../.#./... => #..#/..##/.###/.##.',
 '.#./.#./... => #.../#..#/...#/#.#.',
 '##./.#./... => .#.#/#..#/..#./##.#',
 '#.#/.#./... => .##./#.#./##../#.##',
 '###/.#./... => #.../...#/.#../.#.#',
 '.#./##./... => ####/#.../#.../###.',
 '##./##./... => ##../##../.#../##..',
 '..#/##./... => ##.#/####/..##/.##.',
 '#.#/##./... => .#.#/.##./....

In [180]:
formulas = []
#arr = []
#arr3 = []
d = {".": 0, "#": 1}
for rule in data:
    arr = []
    arr3 = []
    rules = rule.split(" => ")
    for r in rules[0].split("/"):
        arr2 = []
        for c in r:
            arr2.append(d[c])
        arr.append(arr2)
        
    for r in rules[1].split("/"):
        arr4 = []
        for c in r:
            arr4.append(d[c])
        arr3.append(arr4)
    formulas.append([np.array(arr),np.array(arr3)])
    
formulas        

[[array([[0, 0],
         [0, 0]]),
  array([[1, 1, 1],
         [0, 0, 0],
         [1, 0, 0]])],
 [array([[1, 0],
         [0, 0]]),
  array([[1, 0, 0],
         [0, 1, 0],
         [1, 1, 1]])],
 [array([[1, 1],
         [0, 0]]),
  array([[1, 0, 0],
         [1, 1, 1],
         [1, 0, 0]])],
 [array([[0, 1],
         [1, 0]]),
  array([[0, 1, 0],
         [1, 1, 0],
         [1, 0, 1]])],
 [array([[1, 1],
         [1, 0]]),
  array([[0, 1, 0],
         [0, 0, 0],
         [0, 0, 0]])],
 [array([[1, 1],
         [1, 1]]),
  array([[0, 0, 0],
         [1, 0, 0],
         [1, 0, 1]])],
 [array([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
  array([[1, 0, 1, 1],
         [1, 0, 0, 0],
         [0, 0, 1, 1],
         [0, 1, 1, 0]])],
 [array([[1, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]),
  array([[0, 1, 0, 0],
         [1, 0, 0, 1],
         [1, 1, 1, 0],
         [1, 0, 1, 1]])],
 [array([[0, 1, 0],
         [0, 0, 0],
         [0, 0, 0]]),
  array([[0, 0, 0, 0],
       

In [181]:
def fractal(frac_arr):
    #new_arr = []
    if frac_arr.shape[0] % 2 == 0:
        #split in 2x2 arrays
        frac_arr = resample(frac_arr, 2)
    elif frac_arr.shape[0] % 3 == 0:
        #split in 3x3 arrays
        frac_arr = resample(frac_arr, 3)
    return frac_arr

In [103]:
test_arr = fractal(grid)
#test_arr = fractal(np.array([[0,1,0,1],[1,1,1,1],[0,0,0,0],[1,0,1,0]]))

In [183]:
def blockwise(matrix, block=(2, 2)):
    shape = (int(matrix.shape[0] / block[0]), int(matrix.shape[1] / block[1])) + block
    strides = (matrix.strides[0] * block[0], matrix.strides[1] * block[1]) + matrix.strides
    return as_strided(matrix, shape=shape, strides=strides)

def block_join(blocks):
    l = len(blocks)
    if l % 2 == 0:
        l = l / 2
    elif l % 3 == 0:
        l = l / 3
    else:
        print("error")
    return np.vstack(np.hsplit(np.hstack(blocks), l))
def itter(grid):
    new_arr = []
    for i, part in enumerate(grid):
        #print(part)
        tile = transformTile(part)
        #print(tile)
        new_arr.append(tile.tolist())
        #npNicePrint(tile)
        #print(grid)
    grid = block_join(new_arr)
    return grid

grid = np.array([[0,1,0],[0,0,1],[1,1,1]])    
for x in range(5):
    grid = fractal(grid)
    #print(grid)
    grid = itter(grid)
    npNicePrint(grid)
print(sum(sum(grid)))

error
...#
.##.
#..#
#.#.

#...#.
.#.##.
####.#
#...#.
#####.
#..#.#

.#.#..#..
##..#.###
#.#####..
.#.#...#.
...#####.
...#..#.#
.#..#..#.
......##.
......#.#

#.####..###.
..#.#.#...#.
#.#.#.##....
.##.#...#.##
....###.#.##
###...#...#.
.###....#.#.
##..#.##.##.
........#.##
###.###...#.
.###.####.#.
##..##...##.

#...#.
.#....
###...
.#.#..
....#.
...###
#..#..
######
#..#..
.#.#..
##.###
#.##..
#..#..
######
#..#..
#..#..
.#.###
####..
#..#..
###.#.
#..###
#..#..
######
#..#..
#...#.
.#....
###...
.#.#..
...###
...#..
#..#..
.#.###
####..
.#.#..
##.###
#.##..
#..#..
###.#.
#..###
#..#..
###.#.
#..###
#...#.
.#....
###...
.#.#..
...###
...#..
.#.#..
...###
...#..
.#.#..
##.###
#.##..

152


In [119]:
def npNicePrint(arr):
    convertDict = {0: ".", 1: "#"}
    s = ""
    for r in arr:
        for c in r:
            s += convertDict[c]
        s += "\n"
    print(s)
def resample(arr, N):
    A = []
    for v in np.vsplit(arr, arr.shape[0] // N):
        A.extend([*np.hsplit(v, arr.shape[0] // N)])
    return np.array(A)

In [95]:
def getAllConfigurations(arr):
    configurationList = [arr]
    configurationList.append(np.fliplr(arr))
    for i in range(3):
        arr = np.rot90(arr)
        configurationList.append(arr)
        configurationList.append(np.fliplr(arr))
    return configurationList

def checkLineUp(arr1, arr2):
    con1 = getAllConfigurations(arr1)
    #con2 = getAllConfigurations(arr2)
    for grid1 in con1:
        #print(grid1,arr2)
        if np.array_equal(grid1,arr2):
            return True
    return False

def transformTile(arr1):
    for tile in formulas:
        if checkLineUp(arr1,tile[0]):
            return tile[1]

In [8]:
getAllConfigurations(grid)

[array([[0, 1, 0],
        [0, 0, 1],
        [1, 1, 1]]),
 array([[0, 1, 0],
        [1, 0, 0],
        [1, 1, 1]]),
 array([[0, 1, 1],
        [1, 0, 1],
        [0, 0, 1]]),
 array([[1, 1, 0],
        [1, 0, 1],
        [1, 0, 0]]),
 array([[1, 1, 1],
        [1, 0, 0],
        [0, 1, 0]]),
 array([[1, 1, 1],
        [0, 0, 1],
        [0, 1, 0]]),
 array([[1, 0, 0],
        [1, 0, 1],
        [1, 1, 0]]),
 array([[0, 0, 1],
        [1, 0, 1],
        [0, 1, 1]])]