In [75]:
import helpers
import numpy as np
import math
import re
from copy import deepcopy

data = """>>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>"""
with open("input_17.txt", 'r') as f:
    data = f.read().rstrip()

moves = {'>': np.array((1,0)), '<': np.array((-1,0))}
    
blocks = """####

.#.
###
.#.

..#
..#
###

#
#
#
#

##
##"""

blocks = [x.split('\n') for x in blocks.split('\n\n')]
blocks
blocks_coords = []

for block in blocks:
    block_coord = []
    start = np.array([0,0])
    for row in reversed(block):
        start[0] = 0
        for char in row:
            if char == "#":
                block_coord.append(deepcopy(start))
            start += np.array([1,0])
        start[1] += 1
    blocks_coords.append(block_coord)
blocks_coords    
data

'>><>>><<<>>><<>>>><<<>>>><<><>>><<<<>><<<><<<>><<<<>><<>>>><<>><<<><>><><<<>><<<<>>>><<>>><><<>>><<><<<<>>><<>>><>><<<<>><<<<>><<><<>>>><<<>>><<>>>><<<><><><<>>>><<>><<>><>>><<<>><<>>><<<<>>><><<<><<<<><<<<><<<<>>>><>>>><<<>>>><>>><>>><<<<>>><<<<><<<<>>><>>>><<>>>><<<<>>>><<<><<><<<>>>><>>><<<<>>><<<><<>>><<<<>>>><<<>><>><>><<<<>>>><><>>>><<<<>>>><<><<<<><<<<>>>><<>>><<>><<<><<<><<<<>>><<<>>><<>>>><<<>>>><>>>><<<>><<<>>><<<<>>><<>>><<<<>><<>>>><><<<<>>><><>><>><<<>>><<<>><>>>><<<<>>><<<<>>><<<<>><<<<>>><<>>>><>>>><<<>>><<<<><<<>><><<<<>>>><<<>><<<<>>>><<>><<<><<<<><<<<>>>><<<>>>><<>><><<<>><<>>>><<<>><<<>>>><>>>><><<<<><><<>>><<<>><<>>>><<<>><<>>>><<>>><<<<><<<><<>><<<>><>><<<>>>><><>>>><<<><>>>><<<>>>><<>><<>><<<<><<<>>><<<>><<<<>>><>><<>>><<<<>>>><<<><<><<>><<<<>>><<><<<<>>><>>><<>>><<>><<><><<>>>><<><<<<>>><<<<>>><<<<>>>><<>>>><>><<<<>><<<<>>><>><<<>>>><<><<<>>>><<>>><<>><<<<>><<<><<<<>>><<><<<<>>>><<>>><<<>>>><<<>><<<>>>><>>>><>>><>>><>>><>>><<>>><<><<<<>><<>><<>><>>>><<<<>>><<><<

In [76]:
block_i = 0
move_i = 0
settled = set({})

num_blocks = 2022

while block_i <= num_blocks - 1:
    if len(settled) > 0:
        max_height = max(settled,key=lambda item:item[1])[1]
    else:
        max_height = -1
    delta_movement = np.array([2,max_height+4])
    current_moving_blocks = deepcopy(blocks_coords[block_i%len(blocks_coords)])
    current_moving_blocks = move_block(current_moving_blocks, delta_movement)
    while True:
        #move wind
        wind_movement = moves[data[move_i%len(data)]]
        move_i += 1
        potential_moving_blocks = deepcopy(move_block(current_moving_blocks, wind_movement))
        if not check_overlap(potential_moving_blocks):
            current_moving_blocks = potential_moving_blocks
        #move down    
        potential_moving_blocks = deepcopy(move_block_down(current_moving_blocks))
        if check_overlap(potential_moving_blocks):
            break
        current_moving_blocks = potential_moving_blocks
    for coord in current_moving_blocks:
        settled.add(tuple(coord))
    block_i += 1
max(settled,key=lambda item:item[1])[1] + 1

3153

In [67]:
settled

{(2, 0), (2, 2), (3, 0), (3, 1), (3, 2), (3, 3), (4, 0), (4, 2), (5, 0)}

In [13]:
settled = set({})
max(settled,key=lambda item:item[1])

ValueError: max() arg is an empty sequence

In [49]:
block_i = 0
while block_i <= 12 - 1:
    if len(settled) > 0:
        max_height = max(settled,key=lambda item:item[1])[1]
    else:
        max_height = -1
    delta_movement = np.array([2,max_height+4])
    current_moving_blocks = deepcopy(blocks_coords[block_i%len(blocks_coords)])
    print(current_moving_blocks)
    current_moving_blocks = move_block(current_moving_blocks, delta_movement)
    #current_moving_blocks = move_block_down(current_moving_blocks)
    print(current_moving_blocks)
    print("\n")
    block_i += 1

[array([0, 0]), array([1, 0]), array([2, 0]), array([3, 0])]
[array([2, 3]), array([3, 3]), array([4, 3]), array([5, 3])]


[array([1, 0]), array([0, 1]), array([1, 1]), array([2, 1]), array([1, 2])]
[array([3, 3]), array([2, 4]), array([3, 4]), array([4, 4]), array([3, 5])]


[array([0, 0]), array([1, 0]), array([2, 0]), array([2, 1]), array([2, 2])]
[array([2, 3]), array([3, 3]), array([4, 3]), array([4, 4]), array([4, 5])]


[array([0, 0]), array([0, 1]), array([0, 2]), array([0, 3])]
[array([2, 3]), array([2, 4]), array([2, 5]), array([2, 6])]


[array([0, 0]), array([1, 0]), array([0, 1]), array([1, 1])]
[array([2, 3]), array([3, 3]), array([2, 4]), array([3, 4])]


[array([0, 0]), array([1, 0]), array([2, 0]), array([3, 0])]
[array([2, 3]), array([3, 3]), array([4, 3]), array([5, 3])]


[array([1, 0]), array([0, 1]), array([1, 1]), array([2, 1]), array([1, 2])]
[array([3, 3]), array([2, 4]), array([3, 4]), array([4, 4]), array([3, 5])]


[array([0, 0]), array([1, 0]), array([2, 0

In [21]:
from functools import partial

def move_block(cmb, movement):
    return [x + movement for x in cmb]

move_block_down = partial(move_block, movement=np.array((0, -1)))

In [58]:
def check_overlap(cmb):
    if min(cmb,key=lambda item:item[0])[0] < 0 or max(cmb,key=lambda item:item[0])[0] >= 7 or min(cmb,key=lambda item:item[1])[1] < 0:
        return True
    if any([tuple(x) in settled for x in cmb]):
        return True
    return False

In [54]:
check_overlap(move_block_down(move_block_down(move_block_down(move_block_down(current_moving_blocks)))))


True

In [45]:
move_block_down(move_block_down(move_block_down(move_block_down(current_moving_blocks))))

[array([ 3, -2]),
 array([ 2, -1]),
 array([ 3, -1]),
 array([ 4, -1]),
 array([3, 0])]

In [50]:
current_moving_blocks

[array([3, 3]), array([2, 4]), array([3, 4]), array([4, 4]), array([3, 5])]